[WIP] Feature/pmp 160 frontend
valueadd-poland/pimp-my-pr pull request #276
Opened 2020-09-18 08:45 UTC by maciejBart99

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/valueadd-poland/pimp-my-pr/blob/master/CONTRIBUTING.md#git-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: #160 

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2020-09-18 08:46 UTC, maciejBart99 commented
![image](https://user-images.githubusercontent.com/49561570/93577278-22a9f700-f99c-11ea-9ba4-27484c791715.png)

2020-09-18 09:38 UTC, maciejBart99 commented
Timeline view - without actual chart
![image](https://user-images.githubusercontent.com/49561570/93582881-60f6e480-f9a3-11ea-84ed-e1050b8d6bb6.png)

2020-10-02 11:15 UTC, maciej-lukasik-va commented
![image](https://user-images.githubusercontent.com/71699490/94917725-624f0380-04b1-11eb-827e-b60060785dff.png)

2020-10-02 12:18 UTC, maciejBart99 commented on libs/pmp-web/repository/repository-pr-timeline/ui-charts/src/lib/double-axis-chart/double-axis-chart.component.ts
> +import {
This component was based on code from this repo:
https://github.com/habi4ek/double-axis-chart

2020-10-05 15:12 UTC, MaciejSikorski commented
![image](https://user-images.githubusercontent.com/30656326/95097583-ed3c3200-072d-11eb-88bc-e4586e537d8b.png)
Here should be the name of the repository.

When changing the repository you see statistics generated for the previous repostiory

2020-10-06 07:15 UTC, MaciejSikorski requested changes

2020-10-14 12:33 UTC, MaciejSikorski approved these changes

2020-10-14 12:33 UTC, merged